# Generated by Django 4.1.5 on 2023-01-17 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='is_open',
            new_name='is_active',
        ),
    ]
